"""
Fallback demo data used when live scraping fails or returns no results.
Prices are realistic as of 2024-2025 Pakistani market.
Includes a wide range of makes, years, and price points for broad search coverage.
"""

FALLBACK_CARS = [
    {
        "title": "Honda Civic Reborn 1.8 VTi Oriel 2007",
        "price": 950_000,
        "price_display": "PKR 9.5 Lacs",
        "city": "Lahore",
        "year": 2007,
        "mileage": 145_000,
        "mileage_display": "145,000 km",
        "transmission": "Automatic",
        "fuel_type": "Petrol",
        "image": None,
        "url": "https://www.pakwheels.com/used-cars/search/-/mk_honda/",
        "score": 0,
        "ai_explanation": None,
    },
    {
        "title": "Honda Civic Reborn 1.8 VTi 2006",
        "price": 820_000,
        "price_display": "PKR 8.2 Lacs",
        "city": "Rawalpindi",
        "year": 2006,
        "mileage": 162_000,
        "mileage_display": "162,000 km",
        "transmission": "Manual",
        "fuel_type": "Petrol",
        "image": None,
        "url": "https://www.pakwheels.com/used-cars/search/-/mk_honda/",
        "score": 0,
        "ai_explanation": None,
    },
    {
        "title": "Honda Civic Reborn 1.8 VTi 2008",
        "price": 1_050_000,
        "price_display": "PKR 10.5 Lacs",
        "city": "Islamabad",
        "year": 2008,
        "mileage": 130_000,
        "mileage_display": "130,000 km",
        "transmission": "Automatic",
        "fuel_type": "Petrol",
        "image": None,
        "url": "https://www.pakwheels.com/used-cars/search/-/mk_honda/",
        "score": 0,
        "ai_explanation": None,
    },
    {
        "title": "Toyota Corolla 2006 GLi Automatic",
        "price": 780_000,
        "price_display": "PKR 7.8 Lacs",
        "city": "Lahore",
        "year": 2006,
        "mileage": 175_000,
        "mileage_display": "175,000 km",
        "transmission": "Automatic",
        "fuel_type": "Petrol",
        "image": None,
        "url": "https://www.pakwheels.com/used-cars/search/-/mk_toyota/",
        "score": 0,
        "ai_explanation": None,
    },
    {
        "title": "Honda City 2006 IDSI Manual",
        "price": 650_000,
        "price_display": "PKR 6.5 Lacs",
        "city": "Karachi",
        "year": 2006,
        "mileage": 155_000,
        "mileage_display": "155,000 km",
        "transmission": "Manual",
        "fuel_type": "Petrol",
        "image": None,
        "url": "https://www.pakwheels.com/used-cars/search/-/mk_honda/",
        "score": 0,
        "ai_explanation": None,
    },
    {
        "title": "Suzuki Mehran VX 2014",
        "price": 480_000,
        "price_display": "PKR 4.8 Lacs",
        "city": "Rawalpindi",
        "year": 2014,
        "mileage": 88_000,
        "mileage_display": "88,000 km",
        "transmission": "Manual",
        "fuel_type": "Petrol",
        "image": None,
        "url": "https://www.pakwheels.com/used-cars/search/-/mk_suzuki/",
        "score": 0,
        "ai_explanation": None,
    },
    {
        "title": "Toyota Corolla Altis 2018 Automatic",
        "price": 2_650_000,
        "price_display": "PKR 26.5 Lacs",
        "city": "Islamabad",
        "year": 2018,
        "mileage": 85_000,
        "mileage_display": "85,000 km",
        "transmission": "Automatic",
        "fuel_type": "Petrol",
        "image": None,
        "url": "https://www.pakwheels.com/used-cars/search/-/mk_toyota/",
        "score": 0,
        "ai_explanation": None,
    },
    {
        "title": "Honda Civic 2016 1.8 Oriel Prosmatec",
        "price": 2_850_000,
        "price_display": "PKR 28.5 Lacs",
        "city": "Lahore",
        "year": 2016,
        "mileage": 68_000,
        "mileage_display": "68,000 km",
        "transmission": "Automatic",
        "fuel_type": "Petrol",
        "image": None,
        "url": "https://www.pakwheels.com/used-cars/search/-/mk_honda/",
        "score": 0,
        "ai_explanation": None,
    },
    {
        "title": "Suzuki Wagon R VXL 2019",
        "price": 1_550_000,
        "price_display": "PKR 15.5 Lacs",
        "city": "Karachi",
        "year": 2019,
        "mileage": 55_000,
        "mileage_display": "55,000 km",
        "transmission": "Manual",
        "fuel_type": "Petrol",
        "image": None,
        "url": "https://www.pakwheels.com/used-cars/search/-/mk_suzuki/",
        "score": 0,
        "ai_explanation": None,
    },
    {
        "title": "Toyota Prius S 2014",
        "price": 2_900_000,
        "price_display": "PKR 29 Lacs",
        "city": "Islamabad",
        "year": 2014,
        "mileage": 92_000,
        "mileage_display": "92,000 km",
        "transmission": "Automatic",
        "fuel_type": "Hybrid",
        "image": None,
        "url": "https://www.pakwheels.com/used-cars/search/-/mk_toyota/",
        "score": 0,
        "ai_explanation": None,
    },

    {
        "title": "Honda City 1.5L i-VTEC 2022",
        "price": 3_450_000,
        "price_display": "PKR 34.5 Lacs",
        "city": "Islamabad",
        "year": 2022,
        "mileage": 28_000,
        "mileage_display": "28,000 km",
        "transmission": "Automatic",
        "fuel_type": "Petrol",
        "image": None,
        "url": "https://www.pakwheels.com/used-cars/search/-/mk_honda/",
        "score": 0,
        "ai_explanation": None,
    },
    {
        "title": "Toyota Corolla Altis 1.6 2021",
        "price": 4_200_000,
        "price_display": "PKR 42 Lacs",
        "city": "Lahore",
        "year": 2021,
        "mileage": 52_000,
        "mileage_display": "52,000 km",
        "transmission": "Automatic",
        "fuel_type": "Petrol",
        "image": None,
        "url": "https://www.pakwheels.com/used-cars/search/-/mk_toyota/",
        "score": 0,
        "ai_explanation": None,
    },
    {
        "title": "Suzuki Swift Automatic 2022",
        "price": 2_350_000,
        "price_display": "PKR 23.5 Lacs",
        "city": "Islamabad",
        "year": 2022,
        "mileage": 18_000,
        "mileage_display": "18,000 km",
        "transmission": "Automatic",
        "fuel_type": "Petrol",
        "image": None,
        "url": "https://www.pakwheels.com/used-cars/search/-/mk_suzuki/",
        "score": 0,
        "ai_explanation": None,
    },
    {
        "title": "Honda Civic RS 1.5 Turbo 2023",
        "price": 6_800_000,
        "price_display": "PKR 68 Lacs",
        "city": "Karachi",
        "year": 2023,
        "mileage": 12_000,
        "mileage_display": "12,000 km",
        "transmission": "Automatic",
        "fuel_type": "Petrol",
        "image": None,
        "url": "https://www.pakwheels.com/used-cars/search/-/mk_honda/",
        "score": 0,
        "ai_explanation": None,
    },
    {
        "title": "Toyota Yaris 1.3 ATIV 2023",
        "price": 3_100_000,
        "price_display": "PKR 31 Lacs",
        "city": "Rawalpindi",
        "year": 2023,
        "mileage": 22_000,
        "mileage_display": "22,000 km",
        "transmission": "Automatic",
        "fuel_type": "Petrol",
        "image": None,
        "url": "https://www.pakwheels.com/used-cars/search/-/mk_toyota/",
        "score": 0,
        "ai_explanation": None,
    },
    {
        "title": "KIA Picanto 1.0 2022",
        "price": 1_950_000,
        "price_display": "PKR 19.5 Lacs",
        "city": "Lahore",
        "year": 2022,
        "mileage": 35_000,
        "mileage_display": "35,000 km",
        "transmission": "Automatic",
        "fuel_type": "Petrol",
        "image": None,
        "url": "https://www.pakwheels.com/used-cars/search/-/mk_kia/",
        "score": 0,
        "ai_explanation": None,
    },
    {
        "title": "Changan Alsvin 1.5 CVT 2023",
        "price": 2_800_000,
        "price_display": "PKR 28 Lacs",
        "city": "Islamabad",
        "year": 2023,
        "mileage": 14_000,
        "mileage_display": "14,000 km",
        "transmission": "Automatic",
        "fuel_type": "Petrol",
        "image": None,
        "url": "https://www.pakwheels.com/used-cars/search/-/mk_changan/",
        "score": 0,
        "ai_explanation": None,
    },
    {
        "title": "Toyota Fortuner 2.7 VVTi 2021",
        "price": 9_500_000,
        "price_display": "PKR 95 Lacs",
        "city": "Islamabad",
        "year": 2021,
        "mileage": 40_000,
        "mileage_display": "40,000 km",
        "transmission": "Automatic",
        "fuel_type": "Petrol",
        "image": None,
        "url": "https://www.pakwheels.com/used-cars/search/-/mk_toyota/",
        "score": 0,
        "ai_explanation": None,
    },
    {
        "title": "Suzuki Alto VXR 2022",
        "price": 1_650_000,
        "price_display": "PKR 16.5 Lacs",
        "city": "Karachi",
        "year": 2022,
        "mileage": 45_000,
        "mileage_display": "45,000 km",
        "transmission": "Manual",
        "fuel_type": "Petrol",
        "image": None,
        "url": "https://www.pakwheels.com/used-cars/search/-/mk_suzuki/",
        "score": 0,
        "ai_explanation": None,
    },
    {
        "title": "Hyundai Tucson 2.0 2022",
        "price": 7_200_000,
        "price_display": "PKR 72 Lacs",
        "city": "Lahore",
        "year": 2022,
        "mileage": 30_000,
        "mileage_display": "30,000 km",
        "transmission": "Automatic",
        "fuel_type": "Petrol",
        "image": None,
        "url": "https://www.pakwheels.com/used-cars/search/-/mk_hyundai/",
        "score": 0,
        "ai_explanation": None,
    },
    {
        "title": "Honda City Aspire 1.3 2020",
        "price": 2_400_000,
        "price_display": "PKR 24 Lacs",
        "city": "Islamabad",
        "year": 2020,
        "mileage": 68_000,
        "mileage_display": "68,000 km",
        "transmission": "Automatic",
        "fuel_type": "Petrol",
        "image": None,
        "url": "https://www.pakwheels.com/used-cars/search/-/mk_honda/",
        "score": 0,
        "ai_explanation": None,
    },
    {
        "title": "Proton Saga 1.3 Standard 2022",
        "price": 1_850_000,
        "price_display": "PKR 18.5 Lacs",
        "city": "Rawalpindi",
        "year": 2022,
        "mileage": 25_000,
        "mileage_display": "25,000 km",
        "transmission": "Automatic",
        "fuel_type": "Petrol",
        "image": None,
        "url": "https://www.pakwheels.com/used-cars/search/-/mk_proton/",
        "score": 0,
        "ai_explanation": None,
    },
    {
        "title": "Toyota Corolla 1.6 GLi 2019",
        "price": 3_200_000,
        "price_display": "PKR 32 Lacs",
        "city": "Faisalabad",
        "year": 2019,
        "mileage": 82_000,
        "mileage_display": "82,000 km",
        "transmission": "Automatic",
        "fuel_type": "Petrol",
        "image": None,
        "url": "https://www.pakwheels.com/used-cars/search/-/mk_toyota/",
        "score": 0,
        "ai_explanation": None,
    },
    {
        "title": "MG HS 1.5T Excite 2023",
        "price": 6_500_000,
        "price_display": "PKR 65 Lacs",
        "city": "Lahore",
        "year": 2023,
        "mileage": 8_000,
        "mileage_display": "8,000 km",
        "transmission": "Automatic",
        "fuel_type": "Petrol",
        "image": None,
        "url": "https://www.pakwheels.com/used-cars/search/-/mk_mg/",
        "score": 0,
        "ai_explanation": None,
    },
    {
        "title": "Honda BR-V i-VTEC 2019",
        "price": 3_800_000,
        "price_display": "PKR 38 Lacs",
        "city": "Islamabad",
        "year": 2019,
        "mileage": 74_000,
        "mileage_display": "74,000 km",
        "transmission": "Automatic",
        "fuel_type": "Petrol",
        "image": None,
        "url": "https://www.pakwheels.com/used-cars/search/-/mk_honda/",
        "score": 0,
        "ai_explanation": None,
    },
    {
        "title": "Suzuki Cultus VXL 2022",
        "price": 2_150_000,
        "price_display": "PKR 21.5 Lacs",
        "city": "Karachi",
        "year": 2022,
        "mileage": 33_000,
        "mileage_display": "33,000 km",
        "transmission": "Manual",
        "fuel_type": "Petrol",
        "image": None,
        "url": "https://www.pakwheels.com/used-cars/search/-/mk_suzuki/",
        "score": 0,
        "ai_explanation": None,
    },
]


def get_fallback_cars() -> list:
    import copy
    return copy.deepcopy(FALLBACK_CARS)
